services:

  beneficiary-interface:
    build: ./Beneficiary-Interface
    ports:
      - ${BENEFICIARY_PORT}:${BENEFICIARY_PORT}
    volumes:
      - ./Beneficiary-Interface:/app
      - /app/node_modules
      - /app/.next
    command: yarn dev -p ${BENEFICIARY_PORT} --hostname 0.0.0.0
    restart: always

  login-hub-interface:
    build: ./Login-Hub-Interface
    ports:
      - ${LOGIN_HUB_PORT}:${LOGIN_HUB_PORT}
    volumes:
      - ./Login-Hub-Interface:/app
      - /app/node_modules
      - /app/.next
    command: yarn dev -p ${LOGIN_HUB_PORT} --hostname 0.0.0.0
    restart: always

  sales-interface:
    build: ./Sales-Interface
    ports:
      - ${SALES_PORT}:${SALES_PORT}
    volumes:
      - ./Sales-Interface:/app
      - /app/node_modules
      - /app/.next
    command: yarn dev -p ${SALES_PORT} --hostname 0.0.0.0
    restart: always

  collections-interface:
    build: ./Collections-Interface
    ports:
      - ${COLLECTIONS_PORT}:${COLLECTIONS_PORT}
    volumes:
      - ./Collections-Interface:/app
      - /app/node_modules
      - /app/.next
    command: yarn dev -p ${COLLECTIONS_PORT} --hostname 0.0.0.0
    restart: always
